### ISSUE TITLE
Algunas indicaciones

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-3-evaluacion-intermedia-DeliaMesonero#1]
Buen trabajo @DeliaMesonero !

### Algunas pistas para acabarlo:

- [x] Limpia e indenta el código (bueno, sobre todo terminar las partes con comentarios `/* */`)
- [x] Obtén los datos del API con un fetch()
- [x] Pon un `<label>` para indicar para qué es cada `<input>` y recuerda asociarlos con el atributo `htmlFor`.
- [x] ¡Anímate a hacer los filtros!
- [x] Verifica el filter de personajes, de manera que incluya si la usuaria ha seleccionado todos los personajes
- [x] Comprueba que los `inputs` tengan algún valor cuando vas a añadir una nueva frase. 
- [x] Revisa los metadatos en `index.html` (`lang`, `title`...)
- [x] Elimina el código comentado, debuggers y consoles
- [x] Elimina archivos sin usar y sus referencias (hay por la carpeta `src/` archivos relacionados con tests).
- [ ] Haz los bonus del ejercicio para que sigas practicando! 

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by igarridomorillas** [comment]
Perfect!
